---
name: Pull request check

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Tests
        shell: pwsh
        run: |
          dotnet new tool-manifest
          dotnet tool install coveralls.net
          dotnet tool restore
          dotnet test /p:CollectCoverage=true  /p:CoverletOutput=../coverage/ /p:MergeWith="../CoverageResults/coverage.json" /p:CoverletOutputFormat=lcov.json -m:1
      - name: Publish coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./tests/coverage/coverage.info
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          dotnet restore
          dotnet build -c Release
